// Generated by Paw.BindingGen

namespace Paw.Core.Engine;

public unsafe partial class GL
{
    public const int MajorVersion = 4;
    public const int MinorVersion = 6;

    public const string SpecCommitHash = "0b449b97cdf1043eef5e1f0e235cbbab6ec10c86";
    public const string SpecCommitDate = "2026-01-26 16:00:09 +0000";
    public const string SpecCommitSubject = "Update generated dates on headers after recent PR";
}
